name: Build ON push

on:
  push:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run ESDB image
        run: docker run -d --name esdbnode -it -p 2113:2113 -p 1113:1113 eventstore/eventstore:latest --insecure --run-projections=All
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x
      - name: Restore dependencies
        run: |
          echo "$PATH"
          dotnet restore
        working-directory: ./src
      - name: Build
        run: dotnet build --no-restore /p:Version=1.0.0
        working-directory: ./src
      - name: Test
        run: dotnet test --no-build --verbosity minimal
        working-directory: ./src

