name: Build ON push

on:
  push:
    branches: [ master ]

jobs:
#  stop-previous-ESDB:
#    runs-on: ubuntu-latest
#    steps:
#      - name: Stop previous ESDB image
#        run: docker stop esdbnode
#      - name: Remove stoppped ESDB image
#        run: docker rm esdbnode
#

  # get-variables:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Read source data
  #       run: |
  #         echo ${GITHUB_REF#refs/tags/}            

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run ESDB image
        run: docker run -d --name esdbnode -it -p 2113:2113 -p 1113:1113 eventstore/eventstore:latest --insecure --run-projections=All
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x
      - name: Restore dependencies
        run: |
          echo "$PATH"
          dotnet restore
        working-directory: ./src
      - name: Build
        run: dotnet build --no-restore
        working-directory: ./src
      - name: Test
        run: dotnet test --no-build --verbosity minimal
        working-directory: ./src

#  cleanup:
#    runs-on: ubuntu-latest
#    if: always()
#    needs: [start-ESDB, build]
#
#    steps:
#      - name: Stop previous ESDB image
#        run: docker stop esdbnode
#      - name: Remove stoppped ESDB image
#        run: docker rm esdbnode

